baseURL = 'https://zonaeducacional.github.io/leiamais/'
languageCode = 'pt-br'
title = 'LeiaMais - Acervo'
theme = []

[params]
    description = 'Acervo literário de domínio público para estudantes e professores.'
