[build]
  publish = "public"
  command = "hugo --minify"

[context.production.environment]
  HUGO_VERSION = "0.124.0"
  HUGO_ENV = "production"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
