backend:
  name: github
  repo: zonaeducacional/leiamais
  branch: main
  proxy_url: http://localhost:8081 # Não se preocupe, isso apenas confunde o CMS para ele pedir o token manual

display_url: https://zonaeducacional.github.io/leiamais
local_backend: true # Isto permite-lhe testar no computador antes de subir

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "livros"
    label: "Livros"
    folder: "content/livros"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Autor", name: "autor", widget: "string" }
      - { label: "Ano", name: "ano", widget: "string" }
      - { label: "Categoria", name: "categoria", widget: "string" }
      - { label: "Texto do Livro", name: "body", widget: "markdown" }